MVCjqueryAjax/MVCjqueryAjax/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCjqueryAjax.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoCorePatientEntities : DbContext
    {
        public DemoCorePatientEntities()
            : base("name=DemoCorePatientEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PatientMaster> PatientMasters { get; set; }
    }
}

MVCjqueryAjax/MVCjqueryAjax/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Rachit\Learnings\.net core\MVCjqueryAjax\MVCjqueryAjax\MVCjqueryAjax\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

MVCjqueryAjax/MVCjqueryAjax/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

MVCjqueryAjax/MVCjqueryAjax/Models/PatientMaster.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCjqueryAjax.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PatientMaster
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string MRN { get; set; }
        [Display(Name ="Patient Name")]
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public int Age { get; set; }
        public string City { get; set; }
    }
}

MVCjqueryAjax/MVCjqueryAjax/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCjqueryAjax.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCjqueryAjax/MVCjqueryAjax/Controllers/PatientController.cs
using MVCjqueryAjax.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCjqueryAjax.Controllers
{
    public class PatientController : Controller
    {
        // GET: Patient
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewAll()
        {
            return View(GetAllPatients());
        }

        public ActionResult AddorEdit(int id=0)
        {
            PatientMaster pat = new PatientMaster();
            return View(pat);
        }
            
        [HttpPost]
        public ActionResult AddorEdit(PatientMaster pat)
        {
            using (Models.DemoCorePatientEntities db = new DemoCorePatientEntities())
            {
                db.PatientMasters.Add(pat);
                db.SaveChanges();
            }
            return Redirect(Url.Action("ViewAll") + "#firsttab");
        }

        IEnumerable<PatientMaster> GetAllPatients()
        {
            using (Models.DemoCorePatientEntities db=new DemoCorePatientEntities())
            {
                return db.PatientMasters.ToList<PatientMaster>();
            }
        }
    }
}

MVCjqueryAjax/MVCjqueryAjax/Controllers/PatientPopController.cs
using MVCjqueryAjax.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCjqueryAjax.Controllers
{
    public class PatientPopController : Controller
    {
        // GET: PatientPop
        Models.DemoCorePatientEntities patDB = new Models.DemoCorePatientEntities();
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult List()
        {
            return Json(patDB.PatientMasters.ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPatient(int id)
        {
            return Json(patDB.PatientMasters.Where(j => j.ID == id).FirstOrDefault(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Add(PatientMaster patient)
        {
            patDB.PatientMasters.Add(patient);
            patDB.SaveChanges();
            return Json(patient);
        }

        public JsonResult Update(PatientMaster patient)
        {
            var pat = patDB.PatientMasters.Where(j => j.ID == patient.ID).FirstOrDefault();
            pat.MRN = patient.MRN;
            pat.PatientName = patient.PatientName;
            pat.Sex = patient.Sex;
            pat.Age = patient.Age;
            pat.City = patient.City;
            patDB.SaveChanges();
            return Json(pat);
        }

        public JsonResult Delete(int id)
        {
            var pat = patDB.PatientMasters.Where(j => j.ID == id).FirstOrDefault();
            patDB.PatientMasters.Remove(pat);
            patDB.SaveChanges();
            return Json(null);
        }
    }
}

MVCjqueryAjax/MVCjqueryAjax/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCjqueryAjax/MVCjqueryAjax/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCjqueryAjax/MVCjqueryAjax/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVCjqueryAjax/MVCjqueryAjax/Views/Patient/AddorEdit.cshtml
@model MVCjqueryAjax.Models.PatientMaster

@{
    ViewBag.Title = "AddorEdit";
    Layout = null;
}



@using (Html.BeginForm("AddorEdit", "Patient", FormMethod.Post, new {onSubmit = "return jQueryAjaxPost(this);" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.MRN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MRN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MRN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PatientName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sex, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

MVCjqueryAjax/MVCjqueryAjax/Views/Patient/Index.cshtml
@{
    ViewBag.Title = "Index";
}

    <ul class="nav nav-tabs">
        <li><a data-toggle="tab" href="#firsttab">View All</a></li>
        <li><a data-toggle="tab" href="#secondtab">Add New</a></li>
    </ul>
    <div class="tab-content">
        <div id="firsttab" class="tab-pane fade in">@Html.Action("ViewAll")</div>
        <div id="secondtab" class="tab-pane fade in">@Html.Action("AddorEdit")</div>
    </div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
    }

MVCjqueryAjax/MVCjqueryAjax/Views/Patient/ViewAll.cshtml
@model IEnumerable<MVCjqueryAjax.Models.PatientMaster>

@{
    ViewBag.Title = "ViewAll";
    Layout = null;
}


<table class="table table-striped table-condensed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MRN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PatientName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sex)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MRN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PatientName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sex)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.ActionLink("Edit", "AddorEdit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

MVCjqueryAjax/MVCjqueryAjax/Views/PatientPop/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="container">
    <h2>Patient Record</h2>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" onclick="clearTextBox();">Add New Employee</button><br /><br />
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    MRN
                </th>
                <th>
                    Patient Name
                </th>
                <th>
                    Sex
                </th>
                <th>
                    Age
                </th>
                <th>
                    City
                </th>
            </tr>
        </thead>
        <tbody class="tbody">
        </tbody>
    </table>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                @*<button type="button" class="close" data-dissmiss="modal"><span aria-hidden="true">×</span></button>*@
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title" id="myModalLabel">Add Patient</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="ID">ID</label>
                        <input type="text" class="form-control" id="ID" placeholder="Id" disabled="disabled" />
                    </div>
                    <div class="form-group">
                        <label for="MRN">MRN</label>
                        <input type="text" class="form-control" id="MRN" placeholder="MRN" />
                    </div>
                    <div class="form-group">
                        <label for="PatientName">PatientName</label>
                        <input type="text" class="form-control" id="PatientName" placeholder="PatientName" />
                    </div>
                    <div class="form-group">
                        <label for="Sex">Sex</label>
                        <input type="text" class="form-control" id="Sex" placeholder="Sex" />
                    </div>
                    <div class="form-group">
                        <label for="Age">Age</label>
                        <input type="text" class="form-control" id="Age" placeholder="Age" />
                    </div>
                    <div class="form-group">
                        <label for="City">City</label>
                        <input type="text" class="form-control" id="City" placeholder="City" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnAdd" onclick="return AddUpdate();">Add</button>
                <button type="button" class="btn btn-primary" id="btnUpdate" style="display:none;" onclick="AddUpdate();">Update</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts {
<script type="text/javascript">
    $(document).ready(function () {
        //alert('test');
        loaddata();
    })

    function clearTextBox() {
        $('#myModalLabel').text('Add New Patient');
        $('#ID').val('');
        $('#MRN').val('');
        $('#PatientName').val('');
        $('#Sex').val('');
        $('#Age').val('');
        $('#City').val('');

        $('#btnAdd').show();
        $('#btnUpdate').hide();
    }

    function loaddata() {
        $.ajax({
            url: "/PatientPop/List",
            type: "GET",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                var html = '';
                $.each(result, function (key, item) {
                    html += '<tr><td>' + item.ID + '</td>';
                    html += '<td>' + item.MRN + '</td>';
                    html += '<td>' + item.PatientName + '</td>';
                    html += '<td>' + item.Sex + '</td>';
                    html += '<td>' + item.City + '</td>';
                    html += '<td><a href="#" onclick="return getbyID(' + item.ID + ')">Edit</a> | <a href="#" onclick="return Delete(' + item.ID + ')">Delete</a></td>';
                    html += '</tr>';
                });
                $('.tbody').html(html);
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        })
    }

    function AddUpdate() {
        var patobj = {
            ID: (($('#ID').val() > 0) ? $('#ID').val() : 0),
            MRN: $('#MRN').val(),
            PatientName: $('#PatientName').val(),
            Sex: $('#Sex').val(),
            Age: $('#Age').val(),
            City: $('#City').val()
        };

        $.ajax({

            url: (($('#ID').val() > 0) ? '/PatientPop/Update':'/PatientPop/Add' ),            
            type: 'POST',
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            data: JSON.stringify(patobj),
            success: function (ready) {
                loaddata();
                $('#myModal').modal('hide');                
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        })
    }

    function getbyID(id) {
        $('#myModalLabel').text('Update Patient');
        $.ajax({
            url: '/PatientPop/GetPatient/' + id,
            type: 'GET',
            contentType: 'application/json;charset=utf-8',
            dataType: 'json',
            success: function (item) {
                $('#ID').val(item.ID);
                $('#MRN').val(item.MRN);
                $('#PatientName').val(item.PatientName);
                $('#Sex').val(item.Sex);
                $('#Age').val(item.Age);
                $('#City').val(item.City);

                $('#myModal').modal('show');
                $('#btnAdd').hide();
                $('#btnUpdate').show();
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        });
        return false;
    }

    function Delete(id) {
        if (confirm('Are you sure to DELETE?')) {

            $.ajax({
                url: '/PatientPop/Delete/' + id,
                dataType: 'json',
                type: 'POST',
                contentType: 'application/json;charset=utf-8',
                success: function (resp) {
                    loaddata();                    
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });
        }
        return false;
    }
</script>
}

MVCjqueryAjax/MVCjqueryAjax/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Patient Registration", "Index", "Patient", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Patient Pop Registration", "Index", "PatientPop", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now - JQuery Ajax - ASP.NET MVC CRUD Operations</p>
        </footer>
    </div>
    <script src="~/Scripts/Scripts.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>